sudo: required
services:
  - docker

before_install:
  - ./scripts/build_test_images.sh

script:
  - ./scripts/run_tests.sh

after_success:
  - ./scripts/push_to_docker.sh

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: full-stack-reference
  env: FullStackReference-env
  bucket_name: elasticbeanstalk-eu-west-2-230836431314
  bucket_path: full-stack-reference
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
